// <auto-generated />
using System;
using CryptoTracker.API.New.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoTracker.API.New.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    [Migration("20250314182712_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoTracker.API.New.Models.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CirculatingSupply")
                        .HasColumnType("decimal(24,2)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("decimal(24,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceChangePercentage24h")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Volume24h")
                        .HasColumnType("decimal(24,2)");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CirculatingSupply = 19401525m,
                            CurrentPrice = 53000.00m,
                            ImageUrl = "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
                            MarketCap = 1028502937621m,
                            Name = "Bitcoin",
                            PriceChangePercentage24h = 2.34m,
                            Symbol = "btc",
                            Volume24h = 31578397452m
                        },
                        new
                        {
                            Id = 2,
                            CirculatingSupply = 120105764m,
                            CurrentPrice = 2950.15m,
                            ImageUrl = "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
                            MarketCap = 354021576329m,
                            Name = "Ethereum",
                            PriceChangePercentage24h = 3.56m,
                            Symbol = "eth",
                            Volume24h = 14935903245m
                        },
                        new
                        {
                            Id = 3,
                            CirculatingSupply = 97881458867m,
                            CurrentPrice = 1.00m,
                            ImageUrl = "https://assets.coingecko.com/coins/images/325/large/Tether.png",
                            MarketCap = 97944489305m,
                            Name = "Tether",
                            PriceChangePercentage24h = 0.01m,
                            Symbol = "usdt",
                            Volume24h = 83140364432m
                        },
                        new
                        {
                            Id = 4,
                            CirculatingSupply = 157204722m,
                            CurrentPrice = 605.73m,
                            ImageUrl = "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png",
                            MarketCap = 95276514971m,
                            Name = "BNB",
                            PriceChangePercentage24h = 0.92m,
                            Symbol = "bnb",
                            Volume24h = 1904643035m
                        },
                        new
                        {
                            Id = 5,
                            CirculatingSupply = 498073742m,
                            CurrentPrice = 151.12m,
                            ImageUrl = "https://assets.coingecko.com/coins/images/4128/large/solana.png",
                            MarketCap = 75234781241m,
                            Name = "Solana",
                            PriceChangePercentage24h = 4.27m,
                            Symbol = "sol",
                            Volume24h = 2718456192m
                        });
                });

            modelBuilder.Entity("CryptoTracker.API.New.Models.PriceDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CryptocurrencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("decimal(24,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(24,2)");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId", "Timestamp");

                    b.ToTable("PriceDataPoints");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            CryptocurrencyId = 1,
                            MarketCap = 957985057131m,
                            Price = 50420.27m,
                            Timestamp = new DateTime(2025, 1, 13, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30563629193.493924m
                        },
                        new
                        {
                            Id = 30,
                            CryptocurrencyId = 1,
                            MarketCap = 940047662987m,
                            Price = 49476.19m,
                            Timestamp = new DateTime(2025, 1, 14, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32091057104.10097m
                        },
                        new
                        {
                            Id = 29,
                            CryptocurrencyId = 1,
                            MarketCap = 924463281352m,
                            Price = 48655.96m,
                            Timestamp = new DateTime(2025, 1, 15, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31050370701.14648m
                        },
                        new
                        {
                            Id = 28,
                            CryptocurrencyId = 1,
                            MarketCap = 934836146013m,
                            Price = 49201.90m,
                            Timestamp = new DateTime(2025, 1, 16, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32051691166.14931m
                        },
                        new
                        {
                            Id = 27,
                            CryptocurrencyId = 1,
                            MarketCap = 919582011913m,
                            Price = 48399.05m,
                            Timestamp = new DateTime(2025, 1, 17, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 33045002234.65497m
                        },
                        new
                        {
                            Id = 26,
                            CryptocurrencyId = 1,
                            MarketCap = 907378627939m,
                            Price = 47756.77m,
                            Timestamp = new DateTime(2025, 1, 18, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31029285591.57498m
                        },
                        new
                        {
                            Id = 25,
                            CryptocurrencyId = 1,
                            MarketCap = 907632854772m,
                            Price = 47770.15m,
                            Timestamp = new DateTime(2025, 1, 19, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31280932749.28673m
                        },
                        new
                        {
                            Id = 24,
                            CryptocurrencyId = 1,
                            MarketCap = 902231060297m,
                            Price = 47485.85m,
                            Timestamp = new DateTime(2025, 1, 20, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31040978540.21982m
                        },
                        new
                        {
                            Id = 23,
                            CryptocurrencyId = 1,
                            MarketCap = 903018306512m,
                            Price = 47527.28m,
                            Timestamp = new DateTime(2025, 1, 21, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30141275269.97648m
                        },
                        new
                        {
                            Id = 22,
                            CryptocurrencyId = 1,
                            MarketCap = 917201896568m,
                            Price = 48273.78m,
                            Timestamp = new DateTime(2025, 1, 22, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32308787415.87921m
                        },
                        new
                        {
                            Id = 21,
                            CryptocurrencyId = 1,
                            MarketCap = 912499884618m,
                            Price = 48026.31m,
                            Timestamp = new DateTime(2025, 1, 23, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30608772320.956351m
                        },
                        new
                        {
                            Id = 20,
                            CryptocurrencyId = 1,
                            MarketCap = 893798774827m,
                            Price = 47042.04m,
                            Timestamp = new DateTime(2025, 1, 24, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32820608520.33114m
                        },
                        new
                        {
                            Id = 19,
                            CryptocurrencyId = 1,
                            MarketCap = 907928926792m,
                            Price = 47785.73m,
                            Timestamp = new DateTime(2025, 1, 25, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32159882328.54748m
                        },
                        new
                        {
                            Id = 18,
                            CryptocurrencyId = 1,
                            MarketCap = 887234826805m,
                            Price = 46696.57m,
                            Timestamp = new DateTime(2025, 1, 26, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32844618359.04262m
                        },
                        new
                        {
                            Id = 17,
                            CryptocurrencyId = 1,
                            MarketCap = 871608903210m,
                            Price = 45874.15m,
                            Timestamp = new DateTime(2025, 1, 27, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 33624851038.50479m
                        },
                        new
                        {
                            Id = 16,
                            CryptocurrencyId = 1,
                            MarketCap = 880002049067m,
                            Price = 46315.90m,
                            Timestamp = new DateTime(2025, 1, 28, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32065654856.18341m
                        },
                        new
                        {
                            Id = 15,
                            CryptocurrencyId = 1,
                            MarketCap = 866202669011m,
                            Price = 45589.61m,
                            Timestamp = new DateTime(2025, 1, 29, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30166039865.54129m
                        },
                        new
                        {
                            Id = 14,
                            CryptocurrencyId = 1,
                            MarketCap = 857895770814m,
                            Price = 45152.41m,
                            Timestamp = new DateTime(2025, 1, 30, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32332641146.30066m
                        },
                        new
                        {
                            Id = 13,
                            CryptocurrencyId = 1,
                            MarketCap = 871667792616m,
                            Price = 45877.25m,
                            Timestamp = new DateTime(2025, 1, 31, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30015819443.3971399m
                        },
                        new
                        {
                            Id = 12,
                            CryptocurrencyId = 1,
                            MarketCap = 873224679367m,
                            Price = 45959.19m,
                            Timestamp = new DateTime(2025, 2, 1, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 33220737866.69445m
                        },
                        new
                        {
                            Id = 11,
                            CryptocurrencyId = 1,
                            MarketCap = 884068336590m,
                            Price = 46529.91m,
                            Timestamp = new DateTime(2025, 2, 2, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31538294766.81459m
                        },
                        new
                        {
                            Id = 10,
                            CryptocurrencyId = 1,
                            MarketCap = 868558200660m,
                            Price = 45713.59m,
                            Timestamp = new DateTime(2025, 2, 3, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30105358056.773133m
                        },
                        new
                        {
                            Id = 9,
                            CryptocurrencyId = 1,
                            MarketCap = 849059460304m,
                            Price = 44687.34m,
                            Timestamp = new DateTime(2025, 2, 4, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 33126571666.04259m
                        },
                        new
                        {
                            Id = 8,
                            CryptocurrencyId = 1,
                            MarketCap = 854427909777m,
                            Price = 44969.89m,
                            Timestamp = new DateTime(2025, 2, 5, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30460705485.409454m
                        },
                        new
                        {
                            Id = 7,
                            CryptocurrencyId = 1,
                            MarketCap = 843745887432m,
                            Price = 44407.68m,
                            Timestamp = new DateTime(2025, 2, 6, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 33089713297.36044m
                        },
                        new
                        {
                            Id = 6,
                            CryptocurrencyId = 1,
                            MarketCap = 834869962461m,
                            Price = 43940.52m,
                            Timestamp = new DateTime(2025, 2, 7, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32592583629.57862m
                        },
                        new
                        {
                            Id = 5,
                            CryptocurrencyId = 1,
                            MarketCap = 819994520167m,
                            Price = 43157.61m,
                            Timestamp = new DateTime(2025, 2, 8, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30177993428.044949m
                        },
                        new
                        {
                            Id = 4,
                            CryptocurrencyId = 1,
                            MarketCap = 824281422162m,
                            Price = 43383.23m,
                            Timestamp = new DateTime(2025, 2, 9, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32063653542.68982m
                        },
                        new
                        {
                            Id = 3,
                            CryptocurrencyId = 1,
                            MarketCap = 805767842494m,
                            Price = 42408.83m,
                            Timestamp = new DateTime(2025, 2, 10, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 31681464637.48136m
                        },
                        new
                        {
                            Id = 2,
                            CryptocurrencyId = 1,
                            MarketCap = 814090712263m,
                            Price = 42846.88m,
                            Timestamp = new DateTime(2025, 2, 11, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 32513854568.13213m
                        },
                        new
                        {
                            Id = 1,
                            CryptocurrencyId = 1,
                            MarketCap = 802630168607m,
                            Price = 42243.69m,
                            Timestamp = new DateTime(2025, 2, 12, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 30053015099.8630631m
                        },
                        new
                        {
                            Id = 62,
                            CryptocurrencyId = 2,
                            MarketCap = 345184572647m,
                            Price = 2876.54m,
                            Timestamp = new DateTime(2025, 1, 13, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15534876821.811719m
                        },
                        new
                        {
                            Id = 61,
                            CryptocurrencyId = 2,
                            MarketCap = 336251075143m,
                            Price = 2802.09m,
                            Timestamp = new DateTime(2025, 1, 14, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16436349488.53233m
                        },
                        new
                        {
                            Id = 60,
                            CryptocurrencyId = 2,
                            MarketCap = 327594821312m,
                            Price = 2729.96m,
                            Timestamp = new DateTime(2025, 1, 15, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15928187156.528322m
                        },
                        new
                        {
                            Id = 59,
                            CryptocurrencyId = 2,
                            MarketCap = 318003503891m,
                            Price = 2650.03m,
                            Timestamp = new DateTime(2025, 1, 16, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16595618653.85418m
                        },
                        new
                        {
                            Id = 58,
                            CryptocurrencyId = 2,
                            MarketCap = 316843035641m,
                            Price = 2640.36m,
                            Timestamp = new DateTime(2025, 1, 17, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16026992477.95483m
                        },
                        new
                        {
                            Id = 57,
                            CryptocurrencyId = 2,
                            MarketCap = 316835370512m,
                            Price = 2640.29m,
                            Timestamp = new DateTime(2025, 1, 18, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15017905818.3067971m
                        },
                        new
                        {
                            Id = 56,
                            CryptocurrencyId = 2,
                            MarketCap = 323086619696m,
                            Price = 2692.39m,
                            Timestamp = new DateTime(2025, 1, 19, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15025793644.6116276m
                        },
                        new
                        {
                            Id = 55,
                            CryptocurrencyId = 2,
                            MarketCap = 313453611366m,
                            Price = 2612.11m,
                            Timestamp = new DateTime(2025, 1, 20, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15127546192.206231m
                        },
                        new
                        {
                            Id = 54,
                            CryptocurrencyId = 2,
                            MarketCap = 316352614442m,
                            Price = 2636.27m,
                            Timestamp = new DateTime(2025, 1, 21, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15069078066.4184494m
                        },
                        new
                        {
                            Id = 53,
                            CryptocurrencyId = 2,
                            MarketCap = 324201592296m,
                            Price = 2701.68m,
                            Timestamp = new DateTime(2025, 1, 22, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16857941533.37271m
                        },
                        new
                        {
                            Id = 52,
                            CryptocurrencyId = 2,
                            MarketCap = 323446729638m,
                            Price = 2695.39m,
                            Timestamp = new DateTime(2025, 1, 23, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15750665883.883213m
                        },
                        new
                        {
                            Id = 51,
                            CryptocurrencyId = 2,
                            MarketCap = 325709680966m,
                            Price = 2714.25m,
                            Timestamp = new DateTime(2025, 1, 24, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15088887631.0032269m
                        },
                        new
                        {
                            Id = 50,
                            CryptocurrencyId = 2,
                            MarketCap = 323223224256m,
                            Price = 2693.53m,
                            Timestamp = new DateTime(2025, 1, 25, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15283760198.52411m
                        },
                        new
                        {
                            Id = 49,
                            CryptocurrencyId = 2,
                            MarketCap = 322000484033m,
                            Price = 2683.34m,
                            Timestamp = new DateTime(2025, 1, 26, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16584572554.37252m
                        },
                        new
                        {
                            Id = 48,
                            CryptocurrencyId = 2,
                            MarketCap = 322625788336m,
                            Price = 2688.55m,
                            Timestamp = new DateTime(2025, 1, 27, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15801397985.220606m
                        },
                        new
                        {
                            Id = 47,
                            CryptocurrencyId = 2,
                            MarketCap = 318703417589m,
                            Price = 2655.86m,
                            Timestamp = new DateTime(2025, 1, 28, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16814516757.52854m
                        },
                        new
                        {
                            Id = 46,
                            CryptocurrencyId = 2,
                            MarketCap = 320362057184m,
                            Price = 2669.68m,
                            Timestamp = new DateTime(2025, 1, 29, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16470210304.23707m
                        },
                        new
                        {
                            Id = 45,
                            CryptocurrencyId = 2,
                            MarketCap = 311124330763m,
                            Price = 2592.70m,
                            Timestamp = new DateTime(2025, 1, 30, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16763361321.65201m
                        },
                        new
                        {
                            Id = 44,
                            CryptocurrencyId = 2,
                            MarketCap = 319668029115m,
                            Price = 2663.90m,
                            Timestamp = new DateTime(2025, 1, 31, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15665668529.76832m
                        },
                        new
                        {
                            Id = 43,
                            CryptocurrencyId = 2,
                            MarketCap = 323709271857m,
                            Price = 2697.58m,
                            Timestamp = new DateTime(2025, 2, 1, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15324725612.217898m
                        },
                        new
                        {
                            Id = 42,
                            CryptocurrencyId = 2,
                            MarketCap = 316001291453m,
                            Price = 2633.34m,
                            Timestamp = new DateTime(2025, 2, 2, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15904303002.592317m
                        },
                        new
                        {
                            Id = 41,
                            CryptocurrencyId = 2,
                            MarketCap = 312839676562m,
                            Price = 2607.00m,
                            Timestamp = new DateTime(2025, 2, 3, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16552220879.84542m
                        },
                        new
                        {
                            Id = 40,
                            CryptocurrencyId = 2,
                            MarketCap = 306242809610m,
                            Price = 2552.02m,
                            Timestamp = new DateTime(2025, 2, 4, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15269387151.240086m
                        },
                        new
                        {
                            Id = 39,
                            CryptocurrencyId = 2,
                            MarketCap = 301018192685m,
                            Price = 2508.48m,
                            Timestamp = new DateTime(2025, 2, 5, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16183324923.35854m
                        },
                        new
                        {
                            Id = 38,
                            CryptocurrencyId = 2,
                            MarketCap = 301250085851m,
                            Price = 2510.42m,
                            Timestamp = new DateTime(2025, 2, 6, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16974043183.94793m
                        },
                        new
                        {
                            Id = 37,
                            CryptocurrencyId = 2,
                            MarketCap = 306062068642m,
                            Price = 2550.52m,
                            Timestamp = new DateTime(2025, 2, 7, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16344086586.19229m
                        },
                        new
                        {
                            Id = 36,
                            CryptocurrencyId = 2,
                            MarketCap = 310009340936m,
                            Price = 2583.41m,
                            Timestamp = new DateTime(2025, 2, 8, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15578949541.123095m
                        },
                        new
                        {
                            Id = 35,
                            CryptocurrencyId = 2,
                            MarketCap = 310977686363m,
                            Price = 2591.48m,
                            Timestamp = new DateTime(2025, 2, 9, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16979657166.62801m
                        },
                        new
                        {
                            Id = 34,
                            CryptocurrencyId = 2,
                            MarketCap = 313792015707m,
                            Price = 2614.93m,
                            Timestamp = new DateTime(2025, 2, 10, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15048434040.5317182m
                        },
                        new
                        {
                            Id = 33,
                            CryptocurrencyId = 2,
                            MarketCap = 310881422458m,
                            Price = 2590.68m,
                            Timestamp = new DateTime(2025, 2, 11, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 16858125684.7168m
                        },
                        new
                        {
                            Id = 32,
                            CryptocurrencyId = 2,
                            MarketCap = 302061273109m,
                            Price = 2517.18m,
                            Timestamp = new DateTime(2025, 2, 12, 17, 42, 4, 257, DateTimeKind.Utc),
                            Volume = 15439494494.55342m
                        });
                });

            modelBuilder.Entity("CryptoTracker.API.New.Models.PriceDataPoint", b =>
                {
                    b.HasOne("CryptoTracker.API.New.Models.Cryptocurrency", "Cryptocurrency")
                        .WithMany("PriceHistory")
                        .HasForeignKey("CryptocurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cryptocurrency");
                });

            modelBuilder.Entity("CryptoTracker.API.New.Models.Cryptocurrency", b =>
                {
                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
